// <auto-generated />
using System;
using AplikacijaZaUpravljanjeSkladistem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikacijaZaUpravljanjeSkladistem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Uloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Nalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojNaloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipNaloga")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Nalozi");

                    b.HasDiscriminator<string>("TipNaloga").HasValue("Nalog");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KolicinaNaStanju")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.StavkaNaloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kolicina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NalogId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("StavkeNaloga");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Otpremnica", b =>
                {
                    b.HasBaseType("AplikacijaZaUpravljanjeSkladistem.Models.Nalog");

                    b.Property<string>("Primalac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Otpremnica");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Prijemnica", b =>
                {
                    b.HasBaseType("AplikacijaZaUpravljanjeSkladistem.Models.Nalog");

                    b.Property<string>("Dobavljac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Prijemnica");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Nalog", b =>
                {
                    b.HasOne("AplikacijaZaUpravljanjeSkladistem.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Proizvod", b =>
                {
                    b.HasOne("AplikacijaZaUpravljanjeSkladistem.Models.Kategorija", "Kategorija")
                        .WithMany("Proizvodi")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.StavkaNaloga", b =>
                {
                    b.HasOne("AplikacijaZaUpravljanjeSkladistem.Models.Nalog", "Nalog")
                        .WithMany("Stavke")
                        .HasForeignKey("NalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplikacijaZaUpravljanjeSkladistem.Models.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nalog");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Kategorija", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("AplikacijaZaUpravljanjeSkladistem.Models.Nalog", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
